CREATE SEQUENCE IF NOT EXISTS weather_migrations.hibernate_sequence START 1;
CREATE TABLE IF NOT EXISTS weather_migrations.weather
(
    id INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    City TEXT NOT NULL,
    Time TEXT  NOT NULL,
    Temperature DOUBLE PRECISION NOT NULL,
    Wind_Speed DOUBLE PRECISION NOT NULL,
    Pressure DOUBLE PRECISION NOT NULL,
    Wind_Direction TEXT  NOT NULL,
    Humidity INT NOT NULL,
    PRIMARY KEY (Id)
);