version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  eureka:
    build: ./eureka
    restart: always
    image: eureka:latest
    ports:
      - 9003:9003

  currency:
    build: ./currency
    restart: always
    image: currency:latest
    ports:
      - 9001:9001
    depends_on:
      - db

  weather:
    build: ./weather
    restart: always
    image: weather:latest
    ports:
      - 9002:9002
    depends_on:
      - db

  predict:
    build: ./predict
    restart: always
    image: predict:latest
    ports:
      - 9004:9004