apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      name: weather
      labels:
        app: weather
    spec:
      containers:
        - image: weather
          name: weather
          ports:
            - containerPort: 9002
          imagePullPolicy: IfNotPresent