apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      name: currency
      labels:
        app: currency
    spec:
      containers:
        - image: currency
          name: currency
          ports:
            - containerPort: 9001
          imagePullPolicy: IfNotPresent