#spring:
#  profiles: default
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: my-eureka-server.com
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/