CREATE TABLE IF NOT EXISTS currency_migrations.currency
(
    Date TEXT NOT NULL,
    GBR DOUBLE PRECISION NOT NULL,
    EUR DOUBLE PRECISION NOT NULL,
    CAD DOUBLE PRECISION NOT NULL,
    SGD DOUBLE PRECISION NOT NULL,
    AUD DOUBLE PRECISION NOT NULL,
    USD DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (date)
);